export const FETCH_TODAYS_TASKS_REQUEST = 'FETCH_TODAYS_TASKS_REQUEST';
export const FETCH_TODAYS_TASKS_SUCCESS = 'FETCH_TODAYS_TASKS_SUCCESS';
export const FETCH_TODAYS_TASKS_FAILURE = 'FETCH_TODAYS_TASKS_FAILURE';
