export const FETCH_TODAYS_TASKS_REQUEST = 'FETCH_TODAYS_TASKS_REQUEST';
export const FETCH_TODAYS_TASKS_SUCCESS = 'FETCH_TODAYS_TASKS_SUCCESS';
export const FETCH_TODAYS_TASKS_FAILURE = 'FETCH_TODAYS_TASKS_FAILURE';

export const UPDATE_TODAYS_TASKS_REQUEST = 'UPDATE_TODAYS_TASKS_REQUEST';
export const UPDATE_TODAYS_TASKS_SUCCESS = 'UPDATE_TODAYS_TASKS_SUCCESS';
export const UPDATE_TODAYS_TASKS_FAILURE = 'UPDATE_TODAYS_TASKS_FAILURE';
